#!/usr/bin/env python
#
# Unit tests to make sure we're getting the same results across all implementations

import unittest
import numpy as np
import py_laplace
import np_laplace


class TestLaplaceImplementations(unittest.TestCase):

    def setUp(self):
        self.array_size = (100, 100)
        self.niter = 10
        self.dx = 0.1
        self.dy = 0.1
        self.dx2 = self.dx*self.dx
        self.dy2 = self.dy*self.dy
        self.u = self.getStartingArray()
        self.reference_array = self.getNumpyResult()

    def getStartingArray(self):
        # set the state of the input array, the first row is all 1.0 and everywhere else is 0.0
        arr = np.zeros(self.array_size, dtype=np.float64)
        arr[0] = 1.0
        return arr

    def getNumpyResult(self):
        """return the array generated by the NumPy 2D Laplace implementation.  This is our reference implementation"""

        work_array = self.getStartingArray()
        for _ in range(self.niter):
            np_laplace.num_update(work_array, self.dx2, self.dy2)

        return work_array

    def testPythonResult(self):
        for _ in range(self.niter):
            py_laplace.py_update(self.u, self.dx2, self.dy2)

        np.testing.assert_almost_equal(self.u, self.reference_array)

    def testCythonResult(self):
        import cy_laplace

        for _ in range(self.niter):
            cy_laplace.cy_update(self.u, self.dx2, self.dy2)

        np.testing.assert_almost_equal(self.u, self.reference_array)

    def testCythonCWrapResult(self):
        import cy_wrap_claplace

        for _ in range(self.niter):
            cy_wrap_claplace.cy_update_c_wrap(self.u, self.dx2, self.dy2)

        np.testing.assert_almost_equal(self.u, self.reference_array)

    def testCythonCWrapResult(self):
        import numba_laplace # requires numba, easiest to use Anaconda distribution

        for _ in range(self.niter):
            numba_laplace.numba_update(self.u, self.dx2, self.dy2)

        np.testing.assert_almost_equal(self.u, self.reference_array)


def main():
    unittest.main()

if __name__ == '__main__':
    main()
